[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_COINGECKO_API_KEY = "CG-WudDKPBseqAyu9xczCwpi6JE"
  VITE_API_BASE_URL = "https://api.coingecko.com/api/v3"
  VITE_APP_TITLE = "Crypto Price Tracker"
  VITE_REFRESH_INTERVAL = "10000"
  # Configure secrets scanning for client-side environment variables
  # These are intentionally public, rate-limited API credentials for client use
  SECRETS_SCAN_ENABLED = "false"

# Redirect all requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
