[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_COINGECKO_API_KEY = "CG-WudDKPBseqAyu9xczCwpi6JE"
  VITE_API_BASE_URL = "https://api.coingecko.com/api/v3"
  VITE_APP_TITLE = "Crypto Price Tracker"
  VITE_REFRESH_INTERVAL = "10000"
  VITE_DEBUG_API = "true"
  # Configure secrets scanning for client-side environment variables
  # These are intentionally public, rate-limited API credentials for client use
  SECRETS_SCAN_ENABLED = "false"

# Configure proper MIME types for static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jsx"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Content-Type = "font/woff2"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff"
  [headers.values]
    Content-Type = "font/woff"
    Cache-Control = "public, max-age=31536000, immutable"

# Force specific MIME types for critical files
[[redirects]]
  from = "/src/main.jsx"
  to = "/src/main.jsx"
  status = 200
  force = true
  headers = {Content-Type = "text/javascript; charset=utf-8"}

# Serve Vite assets with correct MIME types
[[redirects]]
  from = "/assets/*.js"
  to = "/assets/:splat.js"
  status = 200
  force = true
  headers = {Content-Type = "text/javascript; charset=utf-8"}

[[redirects]]
  from = "/assets/*.mjs"
  to = "/assets/:splat.mjs"
  status = 200
  force = true
  headers = {Content-Type = "text/javascript; charset=utf-8"}

[[redirects]]
  from = "/assets/*.css"
  to = "/assets/:splat.css"
  status = 200
  force = true
  headers = {Content-Type = "text/css; charset=utf-8"}

# Serve all JavaScript files with correct MIME type (catch-all for JS)
[[redirects]]
  from = "/*.js"
  to = "/:splat.js"
  status = 200
  force = true
  headers = {Content-Type = "text/javascript; charset=utf-8"}

[[redirects]]
  from = "/*.mjs"
  to = "/:splat.mjs"
  status = 200
  force = true
  headers = {Content-Type = "text/javascript; charset=utf-8"}

# Serve CSS files
[[redirects]]
  from = "/*.css"
  to = "/:splat.css"
  status = 200
  force = true
  headers = {Content-Type = "text/css; charset=utf-8"}

# Serve other static assets
[[redirects]]
  from = "/*.json"
  to = "/:splat.json"
  status = 200
  force = true
  headers = {Content-Type = "application/json; charset=utf-8"}

[[redirects]]
  from = "/*.png"
  to = "/:splat.png"
  status = 200
  force = true
  headers = {Content-Type = "image/png"}

[[redirects]]
  from = "/*.ico"
  to = "/:splat.ico"
  status = 200
  force = true
  headers = {Content-Type = "image/x-icon"}

# SPA fallback - this MUST be last and should NOT be forced
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["*"], Country = ["*"]}
